version: "3"

services:

  synthea:
    image: synthea
    container_name: site
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres@postgres/fhir
    depends_on:
      - mongodb
      - db
    volumes:
      - opt:/opt
      - syntheticmass_htdocs:/var/www/html
      - /home/hossein/dev/synthetichealth/syntheticmass/site:/usr/src/service
      - /tmp:/tmp
      - /home/hossein:/home/hossein
    working_dir: /usr/src/service
    command: npm start

  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  db:
    image: mdillon/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /tmp:/tmp
      - /home/hossein:/home/hossein

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8090:8080


volumes:
  postgres_data:
    external: true
  syntheticmass_htdocs:
    external: true
  opt:
    external: true






